### PR TITLE
Milestone2

### PR DESCRIPTION
**Pull request by joshuaoivie**
Dear Code Reviewer,

Thank you for taking the time to review my project. This pull request contains the following additional changes:

- Add Featured Stories, Sponsored Insights and Rankings in Column One
- Add Top Story, My Turn, Culture and Travel and More Stories in Column Two
- Add Debate, Opinion, Sponsored Insights and Sign up Form in Column Three
- Add relevant bootstrap classes and custom CSS
- Fix Linter Errors.

Thank you once again. I'm looking forward to your objective review.

Warm Regards,
Josh

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED ♻️ 🔴 
-----------
Hello, @joshuaivie  you are doing an amazing job on this project. 👏 I like you work really hard putting the same image and text content in every section 💪 that's really hard work. 
However, there are a few changes to make to complete this milestone 🛠️ see them below 👇 👀
-----------

- [x] Checks the grammar on your pull request, It's just a comma. Use Grammarly which helps you a lot with the grammar. 
- [x] Do not commit files that are not related to the project. Instead, add them to the .gitignore file. You have this `.gitattributes` please remove it or add it to `.gitignore`
- [x] On tablet mobile after Opinions section, The `sponsored insight` and `free sign up` are not with the proper width. Please fix this. 
- [x] The order of the section on your mobile size is wrong. Please follow the same order from the original one. See the order below 
   👇 
 - TOP STORY
 - FEATURED STORIES
 - THE DEBATE
 - OPINION
 - SPONSORED INSIGHT
 - MORE STORIES
 - LATEST NEWS
 - MY TURN
 - CULTURE & TRAVEL
 - SPONSORED INSIGHT
 - FREE SIGN UP
 - SPONSORED INSIGHT
 --------------
 Make the required changes and send it again for review 👍 💪 
HAPPY CODING!!!

programming-happy-fast-gif

**Comment by joshuaoivie** [comment]
Dear Code Reviewer,

Thank you for taking the time to review my project.  In addition to the earlier changes for this pull request, I have made additional changes based on @BrianSammit's review. The new changes are:

- Remove the .gittributtes file from the project.
- Modify column widths
- Reorder sections on mobile view.

The changes are in addition to the original changes which are: 

- Add Featured Stories, Sponsored Insights and Rankings in Column One
- Add Top Story, My Turn, Culture and Travel and More Stories in Column Two
- Add Debate, Opinion, Sponsored Insights and Sign up Form in Column Three
- Add relevant bootstrap classes and custom CSS
- Fix Linter Errors.

Thank you once again. I'm looking forward to your objective review.

Warm Regards,
Josh

**Review by wathigo — APPROVED** [review]
## APPROVED :heavy_check_mark: 
Great job working on the requested changes.


**You may proceed to the next milestone.**

**Happy Coding :computer: 
Simon Wathigo**

**Comment by joshuaoivie** [comment]
Thank you for your review @wathigo

**Pull request merged**
